# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: build rust-brotli fork
      run: cd rust-brotli/c && make
    - name: Restore dependencies
      run: cd csharp && dotnet restore
    - name: Build
      run: cd csharp && dotnet build --no-restore && dotnet build --no-restore -c Release
    - name: Test
      run: cd csharp && dotnet test --no-build --verbosity normal && dotnet test --no-build --verbosity normal -c Release
    - name: Create nuget package
      run: cd csharp && dotnet pack --no-build --output nupkgs
    - name: Publish build outputs
      uses: actions/upload-artifact@v4
      with:
        path: csharp/lib/bin/x64/Release/
        name: ${{ matrix.os }}
      

